### ISSUE TITLE
cdn.mathjax.org end-of-life

### ISSUE THREAD

**Issue by pkra** [SamyPesse/react-mathjax#1]
See https://www.mathjax.org/cdn-shutting-down/ for more details on migrating to another CDN service.

**Comment by pyramation** [comment]
Hey @pkra nice to see you here! I'm trying to help, so made a pull request: https://github.com/SamyPesse/react-mathjax/pull/7

**Comment by SamyPesse** [comment]
Fixed in `1.0.0`
