### ISSUE TITLE
MathML input

### ISSUE THREAD

**Issue by mehdisadeghi** [SamyPesse/react-mathjax#13]
I want to enter MathML code and have it rendered. I tried to change configuration as described in MathJax website in order to use mml2jax, content-mathml.js and mml3.js however it didn't work. Is it possible to enter MathML instead of TeX?

**Comment by wooloba** [comment]
Hi,
Have you figured a way to solve this problem?

**Comment by mehdisadeghi** [comment]
@mehdisadeghi I created my own react mathjax [component](https://github.com/mehdisadeghi/react-mathjax-preview).
