### ISSUE TITLE
The Mathjax CDN end of life. Not updated on NPM

### ISSUE THREAD

**Issue by N0K0** [SamyPesse/react-mathjax#16]
https://www.mathjax.org/cdn-shutting-down/

And:
https://www.npmjs.com/package/react-mathjax
`samypesse published 7 months ago`

**Comment by Grahack** [comment]
Also, it could be nice to have the URL configurable for those who want to host MathJax themselves.

Thanks so far !!!

**Comment by zyxue** [comment]
Any update on this? the one on npm still looks outdated.

**Comment by MatejMazur** [comment]
I need MathJax for my project so I've updated and a little bit extended this package for my usage.

Here it is: [@matejmazur/react-mathjax](https://www.npmjs.com/package/@matejmazur/react-mathjax).

Hope it helps.

**Comment by SamyPesse** [comment]
The URL can be passed using the prop `script`
